version: "1.0"
type: component
data:
  name: omv-services-snapraidaio-configs-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    stateId: 07e2a020-e8b9-11f0-997d-525400be629f
    sorters:
      - dir: asc
        prop: array_name
    store:
      proxy:
        service: SnapRaidAio
        get:
          method: getConfigList
    columns:
      - name: _("Array")
        prop: array_name
        flexGrow: 1
        sortable: true
      - name: _("Scheduled")
        prop: scheduled
        flexGrow: 0
        width: 250
        sortable: true
        cellTemplateName: checkIcon
      - name: _("Config File")
        prop: snapraid_conf
        flexGrow: 2
        sortable: true
    actions:
      - template: create
        execute:
          type: url
          url: "/services/snapraidaio/configs/create/fa4b1c66-ef79-11e5-87a0-0002b3a176b4"
      - template: edit
        execute:
          type: url
          url: "/services/snapraidaio/configs/edit/{{ _selected[0].uuid }}"
      - type: iconButton
        icon: mdi:clock-outline
        tooltip: _("Schedule")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: url
          url: "/services/snapraidaio/configs/schedule/{{ _selected[0].uuid }}"
      - template: delete
        execute:
          type: request
          request:
            service: SnapRaidAio
            method: deleteConfig
            params:
              uuid: "{{ _selected[0].uuid }}"
